apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-sync
  namespace: default
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "fraud-detection-mlops"
        envSlug: "prod"
        secretsPath: "/"
      credentialsRef:
        secretName: infisical-auth
        secretNamespace: default
  managedSecretReference:
    secretName: fraud-api-secrets
    secretNamespace: default